#
# Copyright © 2025 Arm Ltd and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$BuildType = "Release"
)

function X { param([string]$m) if ($LASTEXITCODE -ne 0) { throw $m } }

$ExternalDir          = Join-Path $RepoRoot "external"
$ArgParseDir          = Join-Path $ExternalDir "argparse"
$TosaToolsDir         = Join-Path $ExternalDir "tosa-tools"
$TosaSerLibDir        = Join-Path $TosaToolsDir "serialization"
$VgfEncoderDir        = Join-Path $ExternalDir "vgf_encoder"

# FlatBuffers bits produced by serialization build
$FlatbuffersInstall   = Join-Path $ExternalDir "flatbuffers-install"
$FlatbuffersConfigDir = (Join-Path $FlatbuffersInstall 'lib\cmake\flatbuffers') -replace '\\','/'
$FlatcExe             = (Join-Path $TosaSerLibDir 'third_party\flatbuffers\flatc.exe') -replace '\\','/'

# Build & Install argparse
$ArgparseBuild   = Join-Path $ExternalDir "argparse-build"
$ArgparseInstall = Join-Path $ExternalDir "argparse-install"
if (Test-Path $ArgparseBuild) { Remove-Item -Recurse -Force $ArgparseBuild }
New-Item -ItemType Directory -Force -Path $ArgparseBuild | Out-Null

& cmake -S $ArgParseDir -B $ArgparseBuild -G "Visual Studio 17 2022" -A x64 `
  -DCMAKE_INSTALL_PREFIX="$ArgparseInstall"
X "CMake configure for argparse failed"

& cmake --build $ArgparseBuild --target INSTALL --config $BuildType
X "Installing argparse failed"

# Build VGF
$VgfBuildDir = Join-Path $VgfEncoderDir "build"
if (Test-Path $VgfBuildDir) { Remove-Item -Recurse -Force $VgfBuildDir }
New-Item -ItemType Directory -Path $VgfBuildDir | Out-Null

$VgfCMake = @(
  '-S', $VgfEncoderDir,
  '-B', $VgfBuildDir,
  '-G', 'Visual Studio 17 2022',
  '-A', 'x64',
  "-Dflatbuffers_DIR=$FlatbuffersConfigDir",
  "-DFLATC_PATH=$FlatcExe",
  "-DARGPARSE_PATH=$ExternalDir\argparse",
  "-DJSON_PATH=$ExternalDir\json",
  "-DFLATBUFFERS_PATH=$TosaSerLibDir\third_party\flatbuffers"
)

$env:CMAKE_PREFIX_PATH = "$ArgparseInstall;$env:CMAKE_PREFIX_PATH"

Write-Host 'Invoking CMake for VGF with args:'
$VgfCMake | ForEach-Object { Write-Host "  $_" }
& cmake @VgfCMake
X "CMake for VGF encoder failed"

& cmake --build $VgfBuildDir --config $BuildType --parallel
X "Build of VGF encoder failed"

$Out = @"
# Auto-generated by build_vgf_encoder.ps1
`$env:CMAKE_PREFIX_PATH = '$($env:CMAKE_PREFIX_PATH)'
"@
Set-Content (Join-Path $ExternalDir "vgf_env.ps1") $Out


