#
# Copyright © 2025 Arm Ltd and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$BuildType = "Release"
)

function AssertZeroExitCode { param([string]$Msg) if ($LASTEXITCODE -ne 0) { throw $Msg } }

$ExternalDir        = Join-Path $RepoRoot "external"
$SpirvHeadersDir    = (Join-Path $ExternalDir "SPIRV-Headers").Replace('\','/')
$SpirvToolsDir      = (Join-Path $ExternalDir "SPIRV-Tools").Replace('\','/')
$SpirvToolsBuild    = Join-Path $SpirvToolsDir "build"
$SpirvToolsInstall  = Join-Path $ExternalDir   "spirv-tools-install"

if (Test-Path $SpirvToolsBuild) { Remove-Item -Recurse -Force $SpirvToolsBuild }
New-Item -ItemType Directory -Force -Path $SpirvToolsBuild | Out-Null

$cmakeArgs = @(
  '-S', $SpirvToolsDir,
  '-B', $SpirvToolsBuild,
  '-G', 'Visual Studio 17 2022',
  '-A', 'x64',
  "-DSPIRV-Headers_SOURCE_DIR=$SpirvHeadersDir",
  '-DSPIRV_WERROR=OFF',
  '-DSPIRV_SKIP_TESTS=ON',
  '-DSPIRV_SKIP_EXECUTABLES=ON',
  '-DSPIRV_TOOLS_BUILD_STATIC=ON',
  '-DBUILD_SHARED_LIBS=OFF',
  "-DCMAKE_INSTALL_PREFIX=$SpirvToolsInstall"
)
& cmake @cmakeArgs
AssertZeroExitCode "CMake configure for SPIRV-Tools failed"

$cfg = if ($BuildType) { $BuildType } else { "Debug" }
& cmake --build $SpirvToolsBuild --config $cfg --target INSTALL
AssertZeroExitCode "Install of SPIRV-Tools failed"

# Find SPIRV-ToolsConfig.cmake
$foundSpvCfg = Get-ChildItem -Path $SpirvToolsInstall -Recurse -Filter 'SPIRV-ToolsConfig.cmake' -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $foundSpvCfg) { throw "SPIRV-ToolsConfig.cmake not found under $SpirvToolsInstall" }
$SpirvToolsConfigDir = $foundSpvCfg.Directory.FullName -replace '\\','/'

# Build & Install SPIRV-Headers
$SpirvHeadersBuild   = Join-Path $SpirvHeadersDir 'build'
$SpirvHeadersInstall = Join-Path $ExternalDir     'spirv-headers-install'
if (Test-Path $SpirvHeadersBuild) { Remove-Item -Recurse -Force $SpirvHeadersBuild }

& cmake -S $SpirvHeadersDir -B $SpirvHeadersBuild -G "Visual Studio 17 2022" -A x64 `
  -DCMAKE_INSTALL_PREFIX="$SpirvHeadersInstall"
AssertZeroExitCode "CMake configure for SPIRV-Headers failed"

& cmake --build $SpirvHeadersBuild --config $BuildType --target INSTALL
AssertZeroExitCode "Install of SPIRV-Headers failed"

# Export env hints exactly like your script
$env:CMAKE_PREFIX_PATH      = "$SpirvToolsInstall;$env:CMAKE_PREFIX_PATH"
$env:CMAKE_PREFIX_PATH      = "$SpirvHeadersInstall;$env:CMAKE_PREFIX_PATH"
$env:SpirvToolsInstall      = $SpirvToolsInstall
$env:SPIRV_TOOLS_BUILD_PATH = $SpirvToolsBuild
$env:SpirvHeadersInstall    = $SpirvHeadersInstall
$SpirvHeadersConfigDir      = (Join-Path $SpirvHeadersInstall 'lib\cmake\SPIRV-Headers') -replace '\\','/'
$SpirvHeadersInc            = (Join-Path $SpirvHeadersInstall 'include') -replace '\\','/'
$env:INCLUDE                = "$SpirvHeadersInc;$env:INCLUDE"

# Persist commonly reused paths to a .ps1 env file
$Out = @"
# Auto-generated by build_spirv_tools.ps1
`$env:SpirvToolsInstall      = '$SpirvToolsInstall'
`$env:SPIRV_TOOLS_BUILD_PATH = '$SpirvToolsBuild'
`$env:SpirvHeadersInstall    = '$SpirvHeadersInstall'
`$env:CMAKE_PREFIX_PATH      = '$($env:CMAKE_PREFIX_PATH)'
"@
Set-Content (Join-Path $ExternalDir "spirv_env.ps1") $Out


