#
# Copyright © 2025 Arm Ltd and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

param(
  [Parameter(Mandatory)][string]$RepoRoot,
  [string]$BuildType = "Release"
)

function AssertNonZero { param([string]$Msg) if ($LASTEXITCODE -ne 0) { throw $Msg } }

$ExternalDir       = Join-Path $RepoRoot "external"
$TosaSerLibDir     = Join-Path $ExternalDir "serialization_lib"
$TosaSerBuildDir   = Join-Path $TosaSerLibDir "build"

if (Test-Path $TosaSerBuildDir) { Remove-Item -Recurse -Force $TosaSerBuildDir }
New-Item -ItemType Directory -Path $TosaSerBuildDir | Out-Null
Push-Location $TosaSerBuildDir

$CMakeArgs = @("-DBUILD_TESTS=ON")
if ($env:OS -notlike "*Windows_NT*") { $env:CXXFLAGS = "-fPIC" }

# Patch attribute.def includes for MSVC
$tosaHandlerPath = Join-Path $TosaSerLibDir "src\tosa_serialization_handler.cpp"
$content = Get-Content $tosaHandlerPath -Raw
if ($content -notmatch '^\s*#ifdef _MSC_VER\s*\r?\n\s*#define\s+DEF_ATTRIBUTE' -and
    $content -match '^\s*#include\s+"attribute\.def"' ) {

    $patchedContent = $content -replace '(?m)^\s*#include\s+"attribute\.def"', @"
#ifdef _MSC_VER
#define DEF_ATTRIBUTE(...)
#endif
#include `"attribute.def`"
#ifdef _MSC_VER
#undef DEF_ATTRIBUTE
#endif
"@
    Set-Content -Path $tosaHandlerPath -Value $patchedContent
    Write-Host "Patched attribute.def includes for MSVC compatibility"
} else {
    Write-Host "Skip patch: attribute.def block already applied"
}

& cmake -S ".." -B "." -G "Visual Studio 17 2022" -A x64 `
  -DCMAKE_CXX_FLAGS="/EHsc /Zc:preprocessor /D_CRT_SECURE_NO_WARNINGS" `
  -DCMAKE_C_FLAGS="/Zc:preprocessor /D_CRT_SECURE_NO_WARNINGS" `
  @CMakeArgs
AssertNonZero "CMake for TOSA serialization library failed"

Write-Host "Building TosaSerialization..."
& cmake --build . --config $BuildType --parallel
AssertNonZero "Build of TOSA serialization library failed"

Pop-Location

# Install FlatBuffers from the sub-build
$FlatbuffersBuild    = Join-Path $TosaSerLibDir 'build\_deps\flatbuffers-build'
$FlatbuffersInstall  = Join-Path $ExternalDir    'flatbuffers-install'

& cmake --install $FlatbuffersBuild --config $BuildType --prefix $FlatbuffersInstall
AssertNonZero "Install of FlatBuffers failed"

$FlatbuffersConfigDir = Join-Path $FlatbuffersInstall 'lib\cmake\flatbuffers'
$FlatbuffersConfig    = Join-Path $FlatbuffersConfigDir 'flatbuffers-config.cmake'
if (-not (Test-Path $FlatbuffersConfig)) { throw "flatbuffersConfig.cmake not found in $FlatbuffersConfigDir" }

$FlatcExe = Join-Path $TosaSerLibDir 'third_party\flatbuffers\flatc.exe'
if (-not (Test-Path $FlatcExe)) { throw "flatc.exe not found at $FlatcExe" }

# Export the same env that your main build uses later
$env:flatbuffers_DIR  = $FlatbuffersConfigDir
$env:flatbuffers_ROOT = $FlatbuffersInstall
$env:CMAKE_PREFIX_PATH = (@($env:CMAKE_PREFIX_PATH, $FlatbuffersInstall) | Where-Object { $_ -and $_.Trim() -ne "" }) -join ';'

# Persist convenience env
$Out = @"
# Auto-generated by build_tosa_serialization_library.ps1
`$env:flatbuffers_DIR  = '$FlatbuffersConfigDir'
`$env:flatbuffers_ROOT = '$FlatbuffersInstall'
`$env:CMAKE_PREFIX_PATH = '$($env:CMAKE_PREFIX_PATH)'
"@
Set-Content (Join-Path $ExternalDir "tosa_ser_env.ps1") $Out


