//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 1.0.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, AvgPool2d)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto input_zp_attr = Attribute({1, 1, 1, 1}, DataType::int8_t);
    auto input_zp = graph.AddTensorConstant(input_zp_attr);

    auto output_zp_attr = Attribute({1, 1, 1, 1}, DataType::int8_t);
    auto output_zp = graph.AddTensorConstant(output_zp_attr);

    auto kernel = Attribute({1, 1}, DataType::int32_t);

    auto stride = Attribute({1, 1}, DataType::int32_t);

    auto pad = Attribute({1, 1, 1, 1}, DataType::int32_t);

    auto acc_type = Attribute({1}, DataType::int32_t);

    auto output = Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddAvgPool2dOperator(input, input_zp, output_zp, kernel, stride, pad, acc_type, output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "AVG_POOL2D", outputStr));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "AVG_POOL2D", outputStr, 5, "uchar"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "AVG_POOL2D", outputStr, 6, "uchar"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1}, "AVG_POOL2D", outputStr, 0));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1}, "AVG_POOL2D", outputStr, 1));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "AVG_POOL2D", outputStr, 2));

    EXPECT_TRUE(testutils::CheckConstant(DataType::int32_t, "AVG_POOL2D", outputStr, 1, 3));
    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "AVG_POOL2D", outputStr));

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "AVG_POOL2D", outputStr));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "AVG_POOL2D", outputStr, 5, "uchar"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "AVG_POOL2D", outputStr, 6, "uchar"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1}, "AVG_POOL2D", outputStr, 0));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1}, "AVG_POOL2D", outputStr, 1));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "AVG_POOL2D", outputStr, 2));

    EXPECT_TRUE(testutils::CheckConstant(DataType::int32_t, "AVG_POOL2D", outputStr, 1, 3));
    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "AVG_POOL2D", outputStr));
}