//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Clamp)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto min_val_val = Tensor::ConvertInt8tToUint32t({1});
    auto min_val = Tensor::CreateAttribute(DataType::int8_t,
                                           std::vector<unsigned int>{ 1 },
                                           min_val_val);

    auto max_val_val = Tensor::ConvertInt8tToUint32t({1});
    auto max_val = Tensor::CreateAttribute(DataType::int8_t,
                                           std::vector<unsigned int>{ 1 },
                                           max_val_val);

    auto output = Tensor::CreateOutput(DataType::int8_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddClampOperator(input,
                            min_val,
                            max_val,
                            output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "CLAMP", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "CLAMP", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "CLAMP", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "CLAMP", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "CLAMP", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "CLAMP", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "CLAMP", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "CLAMP", outputStr);
}