//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Fft2d)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input_real = graph.AddInput(Tensor(DataType::float32_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto input_imag = graph.AddInput(Tensor(DataType::float32_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto inverse = Attribute({1}, DataType::bool_t);
    auto output_real = Tensor(DataType::float32_t, std::vector<unsigned int>{1, 1, 1, 1});

    auto local_bound = Attribute({1}, DataType::bool_t);
    auto output_imag = Tensor(DataType::float32_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddFft2dOperator(input_real, input_imag, inverse, output_real, local_bound, output_imag);
    graph.AddOutput(res[0], 0);
    graph.AddOutput(res[1], 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 0);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 1);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 0);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    testutils::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 1);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
}