//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Fft2d)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input_real = Tensor::CreateInput(DataType::float32_t,
                                          std::vector<unsigned int>{ 1,1,1,1 },
                                          module,
                                          "input_real");

    auto input_imag = Tensor::CreateInput(DataType::float32_t,
                                          std::vector<unsigned int>{ 1,1,1,1 },
                                          module,
                                          "input_imag");

    auto inverse_val = Tensor::ConvertBoolToUint32t({1});
    auto inverse = Tensor::CreateAttribute(DataType::bool_t,
                                           std::vector<unsigned int>{ 1 },
                                           inverse_val);

    auto output_real = Tensor::CreateOutput(DataType::float32_t,
                                            std::vector<unsigned int>{ 1,1,1,1 },
                                            module,
                                            "output_real");

    auto local_bound_val = Tensor::ConvertBoolToUint32t({1});
    auto local_bound = Tensor::CreateAttribute(DataType::bool_t,
                                               std::vector<unsigned int>{ 1 },
                                               local_bound_val);

    auto output_imag = Tensor::CreateOutput(DataType::float32_t,
                                            std::vector<unsigned int>{ 1,1,1,1 },
                                            module,
                                            "output_imag");



    graph->AddFft2dOperator(input_real,
                            input_imag,
                            inverse,
                            output_real,
                            local_bound,
                            output_imag);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "FFT2D", outputStr, true, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "FFT2D", outputStr);
}