//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, FullyConnected)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto weight = Tensor::CreateInput(DataType::int8_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "weight");

    auto bias = Tensor::CreateInput(DataType::int32_t,
                                    std::vector<unsigned int>{ 1,1,1,1 },
                                    module,
                                    "bias");

    auto input_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto input_zp = Tensor::CreateAttribute(DataType::int8_t,
                                            std::vector<unsigned int>{ 1 },
                                            input_zp_val);

    auto weight_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto weight_zp = Tensor::CreateAttribute(DataType::int8_t,
                                             std::vector<unsigned int>{ 1 },
                                             weight_zp_val);

    auto output = Tensor::CreateOutput(DataType::int32_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddFullyConnectedOperator(input,
                                     weight,
                                     bias,
                                     input_zp,
                                     weight_zp,
                                     output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "FULLY_CONNECTED", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "FULLY_CONNECTED", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "FULLY_CONNECTED", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "FULLY_CONNECTED", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "FULLY_CONNECTED", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "FULLY_CONNECTED", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "FULLY_CONNECTED", outputStr);
}