//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 1.0.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Gather)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto values = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto indices = graph.AddInput(Tensor(DataType::int32_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto output = Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddGatherOperator(values, indices, output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "GATHER", outputStr));
    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "GATHER", outputStr));
    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "GATHER", outputStr));

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "GATHER", outputStr));
    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "GATHER", outputStr));
    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "GATHER", outputStr));
}