//
// Copyright © 2023 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.60.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <Writer.hpp>

#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py expecting exception throw of 'Unimplemented methods'.
// Modify it to make it work.
TEST(TOSA2SPIRV_LAYERS, Identity)
{
    IdGenerator idGenerator;

    // Pass in ResId as if coming from a previous layer
    // All datatypes are set to int8_t by default for code generation.
    auto input1 = Tensor::CreateInputFrom(DataType::int8_t,
                                               std::vector<unsigned int>{1,1},
                                               idGenerator.GetNextId());
    auto output = Tensor::CreateOutputTo(DataType::int8_t, std::vector<unsigned int>{1, 1});

    Identity identity(input1,
                           output,
                           idGenerator.GetNextId());

    auto writer = spirvwriter::Writer(idGenerator);

    WriteBoilerplate(writer);

    auto tosaId = writer.WriteExtInstSetImport("TOSA.000080.1");

    writer.WriteMemoryModel();

    GraphInfo graphInfo;
    // Expect a throw of not implemented
    EXPECT_THROW(identityLayer.Write(writer, tosaId, graphInfo), std::exception);
}