//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, MaxPool2d)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto kernel_val = Tensor::ConvertInt32tToUint32t({1,1});
    auto kernel = Tensor::CreateAttribute(DataType::int32_t,
                                          std::vector<unsigned int>{ 2 },
                                          kernel_val);

    auto stride_val = Tensor::ConvertInt32tToUint32t({1,1});
    auto stride = Tensor::CreateAttribute(DataType::int32_t,
                                          std::vector<unsigned int>{ 2 },
                                          stride_val);

    auto pad_val = Tensor::ConvertInt32tToUint32t({1,1,1,1});
    auto pad = Tensor::CreateAttribute(DataType::int32_t,
                                       std::vector<unsigned int>{ 4 },
                                       pad_val);

    auto output = Tensor::CreateOutput(DataType::int8_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddMaxPool2dOperator(input,
                                kernel,
                                stride,
                                pad,
                                output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "MAX_POOL2D", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "MAX_POOL2D", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "MAX_POOL2D", outputStr, 1);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "MAX_POOL2D", outputStr, 2);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "MAX_POOL2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "MAX_POOL2D", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "MAX_POOL2D", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "MAX_POOL2D", outputStr, 1);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "MAX_POOL2D", outputStr, 2);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "MAX_POOL2D", outputStr);
}