//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Negate)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input1 = Tensor::CreateInput(DataType::int8_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "input1");

    auto input1_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto input1_zp = Tensor::CreateAttribute(DataType::int8_t,
                                             std::vector<unsigned int>{ 1 },
                                             input1_zp_val);

    auto output_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto output_zp = Tensor::CreateAttribute(DataType::int8_t,
                                             std::vector<unsigned int>{ 1 },
                                             output_zp_val);

    auto output = Tensor::CreateOutput(DataType::int8_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddNegateOperator(input1,
                             input1_zp,
                             output_zp,
                             output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "NEGATE", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "NEGATE", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "NEGATE", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "NEGATE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "NEGATE", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "NEGATE", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "NEGATE", outputStr, 1, 1);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "NEGATE", outputStr);
}