//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Pad)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input1 = Tensor::CreateInput(DataType::bool_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "input1");

    auto padding = Tensor::CreateInput(DataType::int32_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "padding");

    auto pad_const_val = Tensor::ConvertBoolToUint32t({1});
    auto pad_const = Tensor::CreateAttribute(DataType::bool_t,
                                             std::vector<unsigned int>{ 1 },
                                             pad_const_val);

    auto output = Tensor::CreateOutput(DataType::bool_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddPadOperator(input1,
                          padding,
                          pad_const,
                          output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr);
        spirvwriter::CheckBoolConstant(DataType::bool_t, "PAD", outputStr, true, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr);
        spirvwriter::CheckBoolConstant(DataType::bool_t, "PAD", outputStr, true, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr);
}