//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 1.0.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Pad)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input1 = graph.AddInput(Tensor(DataType::bool_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto padding_attr = Attribute({1, 1, 1, 1}, DataType::int32_t);
    auto padding = graph.AddTensorConstant(padding_attr);

    auto pad_const_attr = Attribute({1, 1, 1, 1}, DataType::bool_t);
    auto pad_const = graph.AddTensorConstant(pad_const_attr);

    auto output = Tensor(DataType::bool_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddPadOperator(input1, padding, pad_const, output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "PAD", outputStr, 1, "uint"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "PAD", outputStr, 2, "bool"));

    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr));

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    EXPECT_TRUE(testutils::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "PAD", outputStr, 1, "uint"));

    EXPECT_TRUE(testutils::CheckConstCompositeTensor({1}, "PAD", outputStr, 2, "bool"));

    EXPECT_TRUE(testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "PAD", outputStr));
}