//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Rescale)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto output = Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1});

    auto input_zp = Attribute({1}, DataType::int8_t);
    auto output_zp = Attribute({1}, DataType::int8_t);
    auto multiplierTensor = Tensor(DataType::int32_t, {1});
    const auto multiplierConstant = graph.AddGraphConstant(multiplierTensor);
    auto multiplier = Attribute(multiplierConstant);

    auto shiftTensor = Tensor(DataType::int8_t, {1});
    const auto shiftConstant = graph.AddGraphConstant(shiftTensor);
    auto shift = Attribute(shiftConstant);

    auto scale32 = Attribute({1}, DataType::bool_t);
    auto double_round = Attribute({1}, DataType::bool_t);
    auto per_channel = Attribute({1}, DataType::bool_t);
    auto input_unsigned = Attribute({1}, DataType::bool_t);
    auto output_unsigned = Attribute({1}, DataType::bool_t);

    const auto res = graph.AddRescaleOperator(input,
                                              output,
                                              input_zp,
                                              output_zp,
                                              multiplier,
                                              shift,
                                              scale32,
                                              double_round,
                                              per_channel,
                                              input_unsigned,
                                              output_unsigned);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    testutils::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 0);
    testutils::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 1);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 4);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 5);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 6);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 7);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 8);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    testutils::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 0);
    testutils::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 1);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 4);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 5);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 6);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 7);
    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 8);
}