//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 1.0.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Rescale)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto multiplier_attr = Attribute({1}, DataType::int32_t);
    auto multiplier = graph.AddTensorConstant(multiplier_attr);

    auto shift_attr = Attribute({1}, DataType::int8_t);
    auto shift = graph.AddTensorConstant(shift_attr);

    auto input_zp_attr = Attribute({1, 1, 1, 1}, DataType::int8_t);
    auto input_zp = graph.AddTensorConstant(input_zp_attr);

    auto output_zp_attr = Attribute({1, 1, 1, 1}, DataType::int8_t);
    auto output_zp = graph.AddTensorConstant(output_zp_attr);

    auto scale32 = Attribute({1}, DataType::bool_t);

    auto rounding_mode = Attribute({1}, DataType::int32_t);

    auto per_channel = Attribute({1}, DataType::bool_t);

    auto input_unsigned = Attribute({1}, DataType::bool_t);

    auto output_unsigned = Attribute({1}, DataType::bool_t);

    auto output = Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddRescaleOperator(input,
                                              multiplier,
                                              shift,
                                              input_zp,
                                              output_zp,
                                              scale32,
                                              rounding_mode,
                                              per_channel,
                                              input_unsigned,
                                              output_unsigned,
                                              output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 6, "uint");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 7, "uchar");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 8, "uchar");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 9, "uchar");

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 0);

    testutils::CheckConstant(DataType::int32_t, "RESCALE", outputStr, 1, 1);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 2);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 3);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 4);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 6, "uint");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 7, "uchar");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 8, "uchar");

    testutils::CheckConstCompositeTensor({1}, "RESCALE", outputStr, 9, "uchar");

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 0);

    testutils::CheckConstant(DataType::int32_t, "RESCALE", outputStr, 1, 1);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 2);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 3);

    testutils::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, 1, 4);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
}