//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Rescale)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto output = Tensor::CreateOutput(DataType::int8_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");

    auto input_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto input_zp = Tensor::CreateAttribute(DataType::int8_t,
                                            std::vector<unsigned int>{ 1 },
                                            input_zp_val);

    auto output_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto output_zp = Tensor::CreateAttribute(DataType::int8_t,
                                             std::vector<unsigned int>{ 1 },
                                             output_zp_val);

    auto multiplier = Tensor(DataType::int32_t,
                             std::vector<unsigned int>{ 1 },
                             graph->GetNextResId());
    module->AddGraphConstant("multiplier", multiplier);

    auto shift = Tensor(DataType::int8_t,
                        std::vector<unsigned int>{ 1 },
                        graph->GetNextResId());
    module->AddGraphConstant("shift", shift);

    auto scale32_val = Tensor::ConvertBoolToUint32t({1});
    auto scale32 = Tensor::CreateAttribute(DataType::bool_t,
                                           std::vector<unsigned int>{ 1 },
                                           scale32_val);

    auto double_round_val = Tensor::ConvertBoolToUint32t({1});
    auto double_round = Tensor::CreateAttribute(DataType::bool_t,
                                                std::vector<unsigned int>{ 1 },
                                                double_round_val);

    auto per_channel_val = Tensor::ConvertBoolToUint32t({1});
    auto per_channel = Tensor::CreateAttribute(DataType::bool_t,
                                               std::vector<unsigned int>{ 1 },
                                               per_channel_val);

    auto input_unsigned_val = Tensor::ConvertBoolToUint32t({1});
    auto input_unsigned = Tensor::CreateAttribute(DataType::bool_t,
                                                  std::vector<unsigned int>{ 1 },
                                                  input_unsigned_val);

    auto output_unsigned_val = Tensor::ConvertBoolToUint32t({1});
    auto output_unsigned = Tensor::CreateAttribute(DataType::bool_t,
                                                   std::vector<unsigned int>{ 1 },
                                                   output_unsigned_val);



    graph->AddRescaleOperator(input,
                              output,
                              input_zp,
                              output_zp,
                              multiplier,
                              shift,
                              scale32,
                              double_round,
                              per_channel,
                              input_unsigned,
                              output_unsigned);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 1);
    spirvwriter::CheckGraphConstant({ 1 }, DataType::int32_t, "RESCALE", outputStr);
    spirvwriter::CheckGraphConstant({ 1 }, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 4);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 5);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 6);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 7);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 8);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 0);
    spirvwriter::CheckConstant(DataType::int8_t, "RESCALE", outputStr, 1, 1);
    spirvwriter::CheckGraphConstant({ 1 }, DataType::int32_t, "RESCALE", outputStr);
    spirvwriter::CheckGraphConstant({ 1 }, DataType::int8_t, "RESCALE", outputStr);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 4);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 5);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 6);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 7);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "RESCALE", outputStr, true, 8);
}