//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Resize)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto scale = Attribute({1, 1, 1, 1}, DataType::int32_t);
    auto offset = Attribute({1, 1}, DataType::int32_t);
    auto border = Attribute({1, 1}, DataType::int32_t);
    auto mode = Attribute({1}, DataType::int32_t);
    auto output = Tensor(DataType::int32_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddResizeOperator(input, scale, offset, border, mode, output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESIZE", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "RESIZE", outputStr, 2);
    testutils::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 3);
    testutils::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 4);
    testutils::CheckConstant(DataType::int32_t, "RESIZE", outputStr, 1, 0);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "RESIZE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESIZE", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "RESIZE", outputStr, 2);
    testutils::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 3);
    testutils::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 4);
    testutils::CheckConstant(DataType::int32_t, "RESIZE", outputStr, 1, 0);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "RESIZE", outputStr);
}