//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Resize)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto scale_val = Tensor::ConvertInt8tToUint32t({1,1,1,1});
    auto scale = Tensor::CreateAttribute(DataType::int32_t,
                                         std::vector<unsigned int>{ 4 },
                                         scale_val);

    auto offset_val = Tensor::ConvertInt8tToUint32t({1,1});
    auto offset = Tensor::CreateAttribute(DataType::int32_t,
                                          std::vector<unsigned int>{ 2 },
                                          offset_val);

    auto border_val = Tensor::ConvertInt8tToUint32t({1,1});
    auto border = Tensor::CreateAttribute(DataType::int32_t,
                                          std::vector<unsigned int>{ 2 },
                                          border_val);

    auto mode_val = Tensor::ConvertInt32tToUint32t({1});
    auto mode = Tensor::CreateAttribute(DataType::int32_t,
                                        std::vector<unsigned int>{ 1 },
                                        mode_val);

    auto output = Tensor::CreateOutput(DataType::int32_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddResizeOperator(input,
                             scale,
                             offset,
                             border,
                             mode,
                             output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

        spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESIZE", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "RESIZE", outputStr, 2);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 3);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 4);
    spirvwriter::CheckConstant(DataType::int32_t, "RESIZE", outputStr, 1, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "RESIZE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

        spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "RESIZE", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "RESIZE", outputStr, 2);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 3);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "RESIZE", outputStr, 4);
    spirvwriter::CheckConstant(DataType::int32_t, "RESIZE", outputStr, 1, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "RESIZE", outputStr);
}