//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Rfft2d)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::float32_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto output_real = Tensor::CreateOutput(DataType::float32_t,
                                            std::vector<unsigned int>{ 1,1,1,1 },
                                            module,
                                            "output_real");

    auto output_imag = Tensor::CreateOutput(DataType::float32_t,
                                            std::vector<unsigned int>{ 1,1,1,1 },
                                            module,
                                            "output_imag");



    graph->AddRfft2dOperator(input,
                             output_real,
                             output_imag);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float32_t, "RFFT2D", outputStr);
}