//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Rsqrt)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input1 = Tensor::CreateInput(DataType::float16_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "input1");

    auto output = Tensor::CreateOutput(DataType::float16_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddRsqrtOperator(input1,
                            output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float16_t, "RSQRT", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float16_t, "RSQRT", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::float16_t, "RSQRT", outputStr);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::float16_t, "RSQRT", outputStr);
}