//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, Slice)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input1 = Tensor::CreateInput(DataType::bool_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "input1");

    auto start_val = Tensor::ConvertInt32tToUint32t({1, 1, 1, 1});
    auto start = Tensor::CreateAttribute(DataType::int32_t,
                                         std::vector<unsigned int>{ 4 },
                                         start_val);

    auto size_val = Tensor::ConvertInt32tToUint32t({1, 1, 1, 1});
    auto size = Tensor::CreateAttribute(DataType::int32_t,
                                        std::vector<unsigned int>{ 4 },
                                        size_val);

    auto output = Tensor::CreateOutput(DataType::bool_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddSliceOperator(input1,
                            start,
                            size,
                            output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "SLICE", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "SLICE", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "SLICE", outputStr, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "SLICE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "SLICE", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "SLICE", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "SLICE", outputStr, 0);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "SLICE", outputStr);
}