//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, Tile)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input1 = graph.AddInput(Tensor(DataType::bool_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto multiples = Attribute({1, 1, 1, 1}, DataType::int32_t);
    auto output = Tensor(DataType::bool_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddTileOperator(input1, multiples, output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "TILE", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TILE", outputStr, 1);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "TILE", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::bool_t, "TILE", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TILE", outputStr, 1);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::bool_t, "TILE", outputStr);
}