//
// Copyright © 2023-2024 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/frontend_generator.py and README

#include <Graph.hpp>
#include <Module.hpp>
#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <TestUtils.hpp>

#include <iostream>

using namespace tosa2spirv;
using namespace graphbuilder;

// Automatically generated by frontend_generator.py
TEST(TOSA2SPIRV_LAYERS, TransposeConv2d)
{
    auto module = Module::Create();
    auto graph = module->AddGraph();

    auto input = Tensor::CreateInput(DataType::int8_t,
                                     std::vector<unsigned int>{ 1,1,1,1 },
                                     module,
                                     "input");

    auto weight = Tensor::CreateInput(DataType::int8_t,
                                      std::vector<unsigned int>{ 1,1,1,1 },
                                      module,
                                      "weight");

    auto bias = Tensor::CreateInput(DataType::int32_t,
                                    std::vector<unsigned int>{ 1,1,1,1 },
                                    module,
                                    "bias");

    auto out_pad_val = Tensor::ConvertInt32tToUint32t({1,1,1,1});
    auto out_pad = Tensor::CreateAttribute(DataType::int32_t,
                                           std::vector<unsigned int>{ 4 },
                                           out_pad_val);

    auto stride_val = Tensor::ConvertInt32tToUint32t({1,1});
    auto stride = Tensor::CreateAttribute(DataType::int32_t,
                                          std::vector<unsigned int>{ 2 },
                                          stride_val);

    auto out_shape_val = Tensor::ConvertInt32tToUint32t({1,1,1,1});
    auto out_shape = Tensor::CreateAttribute(DataType::int32_t,
                                             std::vector<unsigned int>{ 4 },
                                             out_shape_val);

    auto input_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto input_zp = Tensor::CreateAttribute(DataType::int8_t,
                                            std::vector<unsigned int>{ 1 },
                                            input_zp_val);

    auto weight_zp_val = Tensor::ConvertInt8tToUint32t({1});
    auto weight_zp = Tensor::CreateAttribute(DataType::int8_t,
                                             std::vector<unsigned int>{ 1 },
                                             weight_zp_val);

    auto local_bound_val = Tensor::ConvertBoolToUint32t({1});
    auto local_bound = Tensor::CreateAttribute(DataType::bool_t,
                                               std::vector<unsigned int>{ 1 },
                                               local_bound_val);

    auto output = Tensor::CreateOutput(DataType::int32_t,
                                       std::vector<unsigned int>{ 1,1,1,1 },
                                       module,
                                       "output");



    graph->AddTransposeConv2dOperator(input,
                                      weight,
                                      bias,
                                      out_pad,
                                      stride,
                                      out_shape,
                                      input_zp,
                                      weight_zp,
                                      local_bound,
                                      output);

    // Use Module to write the full binary.
    auto binary = module->Write();
    std::string outputStr(tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true));

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "TRANSPOSE_CONV2D", outputStr, 1);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 2);
    spirvwriter::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 3);
    spirvwriter::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 4);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "TRANSPOSE_CONV2D", outputStr, true, 5);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = module->Write();
    outputStr = tosa2spirv::spirvwriter::DisassembleSPIRV(binary, true);

    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 0);
    spirvwriter::CheckConstCompositeTensor({1, 1}, "TRANSPOSE_CONV2D", outputStr, 1);
    spirvwriter::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 2);
    spirvwriter::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 3);
    spirvwriter::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 4);
    spirvwriter::CheckBoolConstant(DataType::bool_t, "TRANSPOSE_CONV2D", outputStr, true, 5);
    spirvwriter::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
}