//
// Copyright © 2023-2025 Arm Ltd and Contributors. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//

// THIS FILE IS GENERATED WITH TOSA 0.80.0.
// See tosa2spirv/python/code_generator.py and README

#include <AssemblyUtils.hpp>
#include <Graph.hpp>
#include <tosa2spirv.hpp>

#include <OpTestUtils.hpp>
#include <gtest/gtest.h>
#include <iostream>

using namespace tosa2spirv::tosa;
// Automatically generated by code_generator.py
TEST(TOSA2SPIRV_LAYERS, TransposeConv2d)
{
    auto module = CreateModule(tosa2spirv::TOSAVersion{});
    auto graph = Graph(module);

    auto input = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto weight = graph.AddInput(Tensor(DataType::int8_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto bias = graph.AddInput(Tensor(DataType::int32_t, std::vector<unsigned int>{1, 1, 1, 1}), 0);

    auto out_pad = Attribute({1, 1, 1, 1}, DataType::int32_t);
    auto stride = Attribute({1, 1}, DataType::int32_t);
    auto out_shape = Attribute({1, 1, 1, 1}, DataType::int32_t);
    auto input_zp = Attribute({1}, DataType::int8_t);
    auto weight_zp = Attribute({1}, DataType::int8_t);
    auto local_bound = Attribute({1}, DataType::bool_t);
    auto output = Tensor(DataType::int32_t, std::vector<unsigned int>{1, 1, 1, 1});

    const auto res = graph.AddTransposeConv2dOperator(input,
                                                      weight,
                                                      bias,
                                                      out_pad,
                                                      stride,
                                                      out_shape,
                                                      input_zp,
                                                      weight_zp,
                                                      local_bound,
                                                      output);
    graph.AddOutput(res, 0);
    graph.FinalizeGraph();

    auto binary = tosa2spirv::WriteToBinary(module);
    std::string outputStr(testutils::DisassembleSPIRV(binary, true));

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 0);
    testutils::CheckConstCompositeTensor({1, 1}, "TRANSPOSE_CONV2D", outputStr, 1);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 2);
    testutils::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 3);
    testutils::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 4);
    testutils::CheckBoolConstant(DataType::bool_t, "TRANSPOSE_CONV2D", outputStr, true, 5);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);

    // Write binary a second time to ensure IDs remain consistent.
    binary = tosa2spirv::WriteToBinary(module);
    outputStr = testutils::DisassembleSPIRV(binary, true);

    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int8_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckInputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 0);
    testutils::CheckConstCompositeTensor({1, 1}, "TRANSPOSE_CONV2D", outputStr, 1);
    testutils::CheckConstCompositeTensor({1, 1, 1, 1}, "TRANSPOSE_CONV2D", outputStr, 2);
    testutils::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 3);
    testutils::CheckConstant(DataType::int8_t, "TRANSPOSE_CONV2D", outputStr, 1, 4);
    testutils::CheckBoolConstant(DataType::bool_t, "TRANSPOSE_CONV2D", outputStr, true, 5);
    testutils::CheckOutputTensor({1, 1, 1, 1}, DataType::int32_t, "TRANSPOSE_CONV2D", outputStr);
}